### ISSUE TITLE
Signing out on alternative tabs isn't automatic

### ISSUE THREAD

**Issue by Modlizard** [NicholasG04/Prom#143]
If you sign out in one browser tab while signed into multiple, you have to refresh the others for them to update.

**Comment by NicholasG04** [comment]
This is far, far more difficult to solve than I initially imagined. onAuthStateChange doesn't seem to work as I thought - it doesn't look it receives events from the internet, only locally. Would have to send cross tab broadcasts I think to do this. Very difficult.
