### ISSUE TITLE
Add user by email and name and admin

### ISSUE THREAD

**Issue by Modlizard** [NicholasG04/Prom#171]
Button on admin panel opens new modal to create user this is relevant for adding teachers although I could just import the teachers using the existing code mmmm hmmmmm... I don't know which is better... at oga underscore dalu um... probably can vouchsafe useful knowledge. 
Sincerest regards and distinguished sentiments,
Big Nick

Well uh you have to put somewhere uhh... the uhh... what's that thing you do when you sign on behalf of someone else...
PP!
what does pp stand for what does pp stand for...
Procuration!
so procurated..?
procurated by...?
Procurated by the Scrum Master.

**Comment by NicholasG04** [comment]
This needs to be migrated to the new 'roles' option in user_meta_data rather than 'admin'
