### ISSUE TITLE
Blockchain

### ISSUE THREAD

**Issue by Modlizard** [NicholasG04/Prom#175]
Blockchain
Blockchain
"Why are the tickets not NFTs"
Blockchain
BlockchainBlockchain

**Comment by john-montgomery2003** [comment]
Prom photos as nfts
Also, a prom in the metaverse?

**Comment by Modlizard** [comment]
Issue is being closed due to substantial triggering of global warming activists amongst other cringe. We're also switching from metal transistor based servers to paper punch-card based computing which is biodegradeable.

**Comment by john-montgomery2003** [comment]
This is a huge issue. As our DPO, this would cause some issues, for example, we may be infringing on a persons right to be forgotten by publishing any personal data to the blockchain.

**Comment by NicholasG04** [comment]
Thanks for pointing this out Jean, great work.
