### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by JacquesRW** [NicholasG04/Prom#190]
It has come to my attention that attempting to calculate Nick's number of software development powerpoints to bitches ratio raises a division by zero error. Possible fix: spend less time with the "cyber mandem".

**Comment by JacquesRW** [comment]
plz nick come back to us

**Comment by JacquesRW** [comment]
:(

**Comment by JacquesRW** [comment]
would like to append "bitches" to "all time bitch count" for my personal pride because I too happen to be alone at the moment

**Comment by Modlizard** [comment]
Counting yourself is not permitted.

**Comment by JacquesRW** [comment]
Further evidence has come to light that highlights the dire situation of this issue.

**Comment by JacquesRW** [comment]
Due to the sensitivity of the circumstances of the evidence, it officially never happened. Action, however, can and must still be taken.

**Comment by RealJammy** [comment]
@NicholasG04 has this been fixed?

**Comment by JacquesRW** [comment]
the issue has not been adressed

**Comment by RealJammy** [comment]
> the issue has not been adressed

@JacquesRW Have you helped Nicholas with this?

**Comment by JacquesRW** [comment]
attempts have been made, but @NicholasG04 has invested yet more time with his so-called "cyber mandem"
