### ISSUE TITLE
Security zone

### ISSUE THREAD

**Issue by Modlizard** [NicholasG04/Prom#207]
Area for security team members only with information regarding who's permitted entry and who isn't.

**Comment by NicholasG04** [comment]
Risk profiling too

**Comment by Modlizard** [comment]
Non-STEM subject students will also be assigned an escalated risk level automatically

**Comment by NicholasG04** [comment]
@ConnorMcF

**Comment by ConnorMcF** [comment]
Any updates? As a security contractor I need to know that my staff will be kept well informed regarding their subjects. Thank you.

**Comment by john-montgomery2003** [comment]
> Any updates? As a security contractor I need to know that my staff will be kept well informed regarding their subjects. Thank you.

No
