### ISSUE TITLE
Add stats to website

### ISSUE THREAD

**Issue by NicholasG04** [NicholasG04/Prom#219]
Power BI is cringe

**Comment by RealJammy** [comment]
I've also taken the design choice to use Comic Sans MS for accessibility purposes. I believe that we should do all if that in pursuit of making the prom accessible to **everyone.**

**Comment by NicholasG04** [comment]
Frustration with row level security means I haven't implemented the full stats, but @JacquesRW has added the only real vital stat to the admin page - number of results (thus number of sales)
