### ISSUE TITLE
Transfer of ownership of Kimberley College Prom

### ISSUE THREAD

**Issue by JacquesRW** [NicholasG04/Prom#235]
Negotiations have begun with Joe Banks of Bingus Ltd pertaining to the acquisition of Kimberley College Prom 2022. On our end, the only requirements are the removal of Nicholas Gregory from his position of power, and to leave him with only being that guy who the pager duty escalates to when we ignore it.

**Comment by RealJammy** [comment]
> Negotiations have begun with Joe Banks of Bingus Ltd pertaining to the acquisition of Kimberley College Prom 2022. On our end, the only requirements are the removal of Nicholas Gregory from his position of power, and to leave him with only being that guy who the pager duty escalates to when we ignore it.

@JacquesRW  I agree with this notion. Nicholas Gregory cannot be trusted due to his censoring of ***IMPORTANT ISSUES*** on this very repository. The team should not stand for this gross misuse of power, and remove Nicholas at the earliest possible moment.

**Comment by RealJammy** [comment]
## @Modlizard  As the
# Scrum Master
### what are your thoughts on this?

**Comment by john-montgomery2003** [comment]
> > Negotiations have begun with Joe Banks of Bingus Ltd pertaining to the acquisition of Kimberley College Prom 2022. On our end, the only requirements are the removal of Nicholas Gregory from his position of power, and to leave him with only being that guy who the pager duty escalates to when we ignore it.
> 
> @JacquesRW  I agree with this notion. Nicholas Gregory cannot be trusted due to his censoring of ***IMPORTANT ISSUES*** on this very repository. The team should not stand for this gross misuse of power, and remove Nicholas at the earliest possible moment. 

Is this suggesting a coup d'etat? Excuse my French

**Comment by RealJammy** [comment]
> > > Negotiations have begun with Joe Banks of Bingus Ltd pertaining to the acquisition of Kimberley College Prom 2022. On our end, the only requirements are the removal of Nicholas Gregory from his position of power, and to leave him with only being that guy who the pager duty escalates to when we ignore it.
> > 
> > 
> > @JacquesRW  I agree with this notion. Nicholas Gregory cannot be trusted due to his censoring of _**IMPORTANT ISSUES**_ on this very repository. The team should not stand for this gross misuse of power, and remove Nicholas at the earliest possible moment.
> 
> Is this suggesting a coup d'état? Excuse my French

yes.

**Comment by john-montgomery2003** [comment]
> > > > Negotiations have begun with Joe Banks of Bingus Ltd pertaining to the acquisition of Kimberley College Prom 2022. On our end, the only requirements are the removal of Nicholas Gregory from his position of power, and to leave him with only being that guy who the pager duty escalates to when we ignore it.
> > > 
> > > 
> > > @JacquesRW  I agree with this notion. Nicholas Gregory cannot be trusted due to his censoring of _**IMPORTANT ISSUES**_ on this very repository. The team should not stand for this gross misuse of power, and remove Nicholas at the earliest possible moment.
> > 
> > Is this suggesting a coup d'état? Excuse my French
> 
> yes.
> 
We need to roll out the guillotine then...

**Comment by Modlizard** [comment]
I concur with all of the above as Nicholas has failed to bring exponential pricing to life in favour of exponential ***irresponsibility***, this ***cannot*** be tolerated any longer.
