### ISSUE TITLE
Create Mail Server

### ISSUE THREAD

**Issue by RandxmStranger** [NicholasG04/Prom#38]
@prom.kim emails please

**Comment by john-montgomery2003** [comment]
any ideas on which mail server you would like to use for this?

**Comment by NicholasG04** [comment]
Since it's free I'll probably just chuck it on my existing mail server, although that could do with an upgrade... Thoughts?

**Comment by NicholasG04** [comment]
There is a cloudflare email redirect set up right now, do we actually need to be able to send emails using this domain? I don't see a point really....
