### ISSUE TITLE
Login/home page not working on Safari

### ISSUE THREAD

**Issue by NicholasG04** [NicholasG04/Prom#60]
![image](https://user-images.githubusercontent.com/33908215/155614871-1c63a001-0b0e-41b8-bc3f-6105fd7626c0.png)

Assigned @john-montgomery2003 as he might be able to test this on Safari on macOS?

**Comment by john-montgomery2003** [comment]
I also experianced this, using it on safari, will find out how to fix, no problem!

**Comment by NicholasG04** [comment]
I'm thinking it could be due to the 100% height on the Box https://github.com/NicholasG04/Prom/blob/master/src/components/Home/Header.tsx#L14 not working... strange though since it should be inheriting fine

**Comment by john-montgomery2003** [comment]
It is infact that line yes, ive tested with removing the height:100% in css in dev tools and it fixes it lovely. It also seems non essential?

**Comment by NicholasG04** [comment]
Interesting, since on Edge (chromium) this causes it to have no height at all thus no blur. Are you sure that removing the height 100% leaves it with any blur on Safari?

**Comment by NicholasG04** [comment]
Please can you check what height `div.css-1elo1xp` is getting? Is it just the header section or the whole page? Since it should be inheriting from that with the 100% height.

**Comment by john-montgomery2003** [comment]
1elo1xp seems to have a height of 0... but 350 padding top, 72 bottom

**Comment by NicholasG04** [comment]
Anything change if you add `height: 100%` to `div.css-j5krh6`?

**Comment by NicholasG04** [comment]
Fixed
